app/item/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Regexp
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from ..models import Item, Usuario


class CriarItemForm(FlaskForm):
    nome = StringField('Nome', validators=[DataRequired(),
                                             Regexp('^[A-Za-z0-9 \s]+$', 0,
										'Campo nome permitido apenas letras e números')                                              
                                                 ])
    quantidade = StringField('Quantidade', validators=[DataRequired(),
                                             Regexp('^[0-9 \s]+$', 0,
										'Campo quantidade permitido apenas números')                                              
                                                 ])

    cadastrar = SubmitField('Salvar')

    #
    def validate_nome(self, field):
        if Item.query.filter_by(nome_i=field.data).first():
            raise ValidationError('Item já cadastrado.')

class EditarItemFormEntrada(FlaskForm):
    nome = StringField('Nome', validators=[DataRequired(),
                                             Regexp('^[A-Za-z0-9 \s]+$', 0,
										'Campo nome permitido apenas letras e números')                                              
                                                 ])
    quantidade = StringField('Quantidade', validators=[DataRequired(),
                                             Regexp('^[0-9 \s]+$', 0,
										'Campo quantidade permitido apenas números')                                              
                                                 ])
    entrada = StringField('Entrada', validators=[
                                             Regexp('[0-9 \s]+$', 0,
										'Campo quantidade permitido apenas números')                                              
                                                 ])
                                                                                                
    cadastrar = SubmitField('Salvar')

class EditarItemFormSaida(FlaskForm):
    nome = StringField('Nome', validators=[DataRequired(),
                                             Regexp('^[A-Za-z0-9 \s]+$', 0,
										'Campo nome permitido apenas letras e números')                                              
                                                 ])
    quantidade = StringField('Quantidade', validators=[DataRequired(),
                                             Regexp('^[0-9 \s]+$', 0,
										'Campo quantidade permitido apenas números')                                              
                                                 ])
    saida = StringField('Saída', validators=[
                                             Regexp('[0-9 \s]+$', 0,
										'Campo quantidade permitido apenas números')                                              
                                                 ])                                                                                                 
    cadastrar = SubmitField('Salvar')

class BuscarItem(FlaskForm):
    nome = StringField('Nome', validators=[DataRequired(),
                                             Regexp('^[A-Za-z0-9 \s]+$', 0,
										'Campo nome permitido apenas letras e números')                                              
                                                 ])
    buscar = SubmitField('Buscar')                                                

# class VisualizarForm(FlaskForm):
#     nome = StringField('Nome', validators=[DataRequired()])
#     quantidade = StringField('Quantidade', validators=[DataRequired()])
#     entrada = StringField('Entrada', validators=[DataRequired()])
    #saida = StringField('Saída', validators=[DataRequired()])

app/item/__init__.py
from flask import Blueprint
  
item = Blueprint('item', __name__)

from . import views

app/item/views.py
from flask import abort, flash, redirect, render_template, url_for, request
from flask_login import current_user, login_required
from . import item
from .forms import CriarItemForm, EditarItemFormEntrada, EditarItemFormSaida #, VisualizarForm
from .. import db
from ..models import Item, Usuario

# from datetime import date
# data_atual = date.today()

@item.route('/itens', methods=['GET', 'POST'])
@login_required
def listar_itens():                             
    itens = Item.query.all()
    return render_template('item/itens.html',
                           itens=itens, title="Itens")
 

@item.route('/add', methods=['GET', 'POST'])
@login_required
def add_item():
    
    form = CriarItemForm()
    
    if form.validate_on_submit():
        item =  Item(nome_i=form.nome.data, quantidade_i=form.quantidade.data)
        try:
            db.session.add(item)
            db.session.commit()
            flash('Item cadastrado com sucesso.')
        except:
            flash('Erro: Já existe um produto com esse nome.')

        return redirect(url_for('item.listar_itens'))
    return render_template('item/item.html',
                            add_item=True, form=form,
                            title="Cadastrar Item")
    #return redirect(url_for('item.listar_itens'))

@item.route('/edit/entrada<int:id>', methods=['GET', 'POST'])
@login_required
def editar_item_entrada(id):

    item = Item.query.get_or_404(id)
    form = EditarItemFormEntrada(obj=item)
 
    if form.validate_on_submit():
        item.nome_i = form.nome.data

        item.quantidade_i = int (form.quantidade.data) + int (form.entrada.data)
       
        # flash(item.quantidade_i )
        try:
            db.session.add(item)
            db.session.commit()
            flash('Item editado com sucesso.')
        except:
            flash('Erro: Já existe um produto com esse nome.')
        return redirect(url_for('item.listar_itens'))

    form.quantidade.data = item.quantidade_i
    form.nome.data = item.nome_i
    
    return render_template('item/item.html',
                            add_item=False, form=form,
                            item=item, title="Editar Item")

@item.route('/edit/saida/<int:id>', methods=['GET', 'POST'])
@login_required
def editar_item_saida(id):

    item = Item.query.get_or_404(id)
    form = EditarItemFormSaida(obj=item)
 
    if form.validate_on_submit():
        item.nome_i = form.nome.data

        item.quantidade_i = int (form.quantidade.data) -  int (form.saida.data)
       
        # flash(item.quantidade_i )
        try:
            db.session.add(item)
            db.session.commit()
            flash('Item editado com sucesso.')
        except:
            flash('Erro: Já existe um produto com esse nome.')
        return redirect(url_for('item.listar_itens'))

    form.quantidade.data = item.quantidade_i
    form.nome.data = item.nome_i
    
    return render_template('item/item.html',
                            add_item=False, form=form,
                            item=item, title="Editar Item")
    

# @item.route('/<int:id>', methods=['GET', 'POST'])
# @login_required
# def visualizar_item(id):

#     item = Item.query.get_or_404(id)
#     form = VisualizarForm(obj=item)

#     form.quantidade.data = item.quantidade_i
#     form.nome.data = item.nome_i
#     return render_template('item/item.html',
#                            form=form,
#                            item=item, title="Visualizar Item")

@item.route('/excluir/<int:id>', methods=['GET', 'POST'])
@login_required
def excluir_item(id):
    
    try:
        item = Item.query.get_or_404(id)
        db.session.delete(item)
        db.session.commit()
        flash('Item removido com sucesso.')
    except:
        flash('Erro ao remover o item')

    return redirect(url_for('item.listar_itens'))
    

app/templates/item/item.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %} 
{% if add_item %}
        Adicionar-Item
    {% else %}
        Atualizar-Item
{% endif %}
{% endblock %}
{% block body %}
<div class="content-section" id="gradient">
 <div class="outer">
    <div class="middle">
      <div class="inner" >
        <div class="center" >
            {% if add_item %}
                <h1 style="text-align:center;">Cadastrar Item</h1>
                <br/>
                 {{ wtf.quick_form(form) }}
                <br/>
                 <a href="{{ request.referrer }}" class="btn btn-default btn-sm">
                 <i class="fa fa-backward "></i> Voltar </a><br/>
            {% elif editar_item_entrada %}
                  <h1 style="text-align:center;">----Atualizar Informações do Item</h1>
                  <br/>
                  {{ wtf.quick_form(form) }}
                  <br/>
                  <a href="{{ request.referrer }}" class="btn btn-default btn-sm">
                  <i class="fa fa-backward "></i> Voltar </a><br/>
              <!-- request.referrer - guarda a tela de onde ele vem, servindo paar voltar  -->
              {% else %}
                  <h1 style="text-align:center;">Atualizar Informações do Item</h1>
                  <br/>
                  {{ wtf.quick_form(form) }}
                  <br/>
                  <a href="{{ request.referrer }}" class="btn btn-default btn-sm">
                  <i class="fa fa-backward "></i> Voltar </a><br/>
            {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/item/itens.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Item{% endblock %}
{% block body %}
<div class="content-section" id="gradient">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">-- Itens --</h1>
        {% if itens %}
          <hr class="intro-divider">
          <div class="center">
         

            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="20%">Nome </th>
                  <th width="15%"> Quantidade </th>
                  <th width="22%"> Entrada</th>
                  <th width="22%"> Saida </th>
                  <th width="21%"> Excluir </th>
                </tr>
              </thead>
              <tbody>
              {% for item in itens %}
                <tr>
                  <td> {{ item.nome_i }} </td>
                  <td> {{ item.quantidade_i }} </td>
                  
                  <td>
                  <a href="{{ url_for('item.editar_item_entrada', id=item.id_i) }}">
                    <i class="fa fa-pencil-square"></i> Entrada de Item
                  </a>
                  </td>

                  <td>
                    <a href="{{ url_for('item.editar_item_saida', id=item.id_i) }}">
                    <i class="fa fa-pencil-square-o"></i> Saída de Item
                    </a>
                  </td>

                  <td>
                    <a href="{{ url_for('item.excluir_item', id=item.id_i) }}">
                      <i class="fa fa-trash"></i> Excluir
                    </a>
                  </td>
                </tr>
                {% endfor %}
                </tbody>
              
              </table>
          
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> Não há itens cadastrados </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('item.add_item') }}" class="btn btn-default btn-sm">
            <i class="fa fa-plus"></i>
            Cadastrar item
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}